### ISSUE TITLE
Reset offset error clarification

### ISSUE THREAD

**Issue by figuernd** [WHOIGit/PhytO-ARM#17]
https://github.com/WHOIGit/PhytO-ARM/blob/4e420955b84deac85c3071124a5bf638a7fe7969/src/phyto_arm/src/winch_node.py#L204

25 bit counter may suffer an overflow when this is triggered, solution is to login to JVL via MacTalk and reset position to 0. Error message should be updated to make this course of action more explicit.

**Comment by rgov** [comment]
Related to #22.
