### ISSUE TITLE
config validation should allow float type default values for lat/lon

### ISSUE THREAD

**Issue by mbrosnahan** [WHOIGit/PhytO-ARM#36]
Currently only accepts int type

**Comment by rgov** [comment]
It works by looking at the types in the example config.

https://github.com/WHOIGit/PhytO-ARM/blob/d7f493fc8f0bad54a2f68c0af40bf4ada0a84d06/configs/example.yaml#L136-L144

You could update these defaults to -99999.99 or something and then it will accept floats.

**Comment by mbrosnahan** [comment]
Addition of a decimal point to example.yaml did the trick.
